
import { ExchangeRates, Currency } from './types';
import { Car as CarIcon, Zap, Shield, Truck, Diamond, BatteryCharging } from 'lucide-react';

export const APP_NAME = "Tubo";
export const CURRENT_YEAR = new Date().getFullYear();
export const MAX_CAR_AGE = 12;
export const MIN_ALLOWED_YEAR = CURRENT_YEAR - MAX_CAR_AGE;

export const CURRENCIES: Currency[] = ['IDR', 'MYR', 'SGD', 'CAD', 'USD'];

// Mock Exchange Rates (Base IDR)
export const EXCHANGE_RATES: ExchangeRates = {
  IDR: 1,
  MYR: 0.00030,
  SGD: 0.000086,
  USD: 0.000064,
  CAD: 0.000087,
};

export const POPULAR_CITIES = [
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Kuala Lumpur, Malaysia",
  "Singapore",
  "Toronto, Canada",
  "Vancouver, Canada",
  "New York, USA",
  "Los Angeles, USA"
];

export const TRANSLATIONS = {
  'English': {
    tagline: "Peer-to-Peer Car Rental",
    findPerfectRide: "Find your perfect ride",
    exploreThousands: "Explore thousands of cars from trusted hosts",
    locationPlaceholder: "Search city or location...",
    pickup: "Pick-up",
    dropoff: "Drop-off",
    time: "Time",
    searchBtn: "Search Available Cars",
    sponsored: "Sponsored Cars",
    viewAll: "View All",
    whyChoose: "Why Choose TUBO?",
    popular: "Popular Near You",
    browseCategory: "Browse by Category",
    testimonials: "What Our Users Say",
    becomeHost: "Become a Host",
    startHosting: "Start Hosting",
    hostDesc: "List your car and start earning passive income today. Join thousands of hosts already on TUBO.",
    favorites: "Favorites",
    favoritesDesc: "Save cars you love to find them easily later.",
    noTrips: "No Upcoming Trips",
    noTripsDesc: "You haven't booked any cars yet. Start exploring!",
    switchHost: "Switch to Host Mode",
    joinHost: "Become a Host",
    hostBenefits: "Manage your listings, check earnings, and communicate.",
    joinBenefits: "Earn extra income by renting out your car.",
    switch: "Switch",
    join: "Join",
    preferences: "Preferences",
    account: "Account",
    currency: "Currency",
    language: "Language",
    accountSettings: "Account Settings",
    paymentMethods: "Payment Methods",
    supportInbox: "Support Inbox",
    logOut: "Log Out",
    home: "Home",
    trips: "Trips",
    profile: "Profile",
    dashboard: "Dashboard",
    listings: "Listings",
    inbox: "Inbox",
    menu: "Menu",
    guestMode: "Guest Mode",
    switchToRenting: "Switch to renting",
    hostSettings: "Host Settings",
    payoutMethods: "Payout Methods",
    bookNow: "Book Now",
    book: "Book",
    perDay: "Per day",
    day: "day",
    cars: "cars",
    locationLabel: "Location",
    change: "Change",
    hostDashboard: "Host Dashboard",
    hostDashboardDesc: "Manage your fleet and earnings.",
    weekly: "Weekly",
    active: "Active",
    listNewCar: "List a New Car",
    earningsTrend: "Earnings Trend",
    recentBookings: "Recent Bookings",
    paid: "Paid",
    verifiedMember: "Verified Member",
    yourListings: "Your Listings",
    hostInbox: "Host Inbox",
    allCities: "All Cities",
    showingResultsFor: "Showing results for"
  },
  'Bahasa Indonesia': {
    tagline: "Sewa Mobil Peer-to-Peer",
    findPerfectRide: "Temukan mobil impianmu",
    exploreThousands: "Jelajahi ribuan mobil dari tuan rumah terpercaya",
    locationPlaceholder: "Cari kota atau lokasi...",
    pickup: "Ambil",
    dropoff: "Kembali",
    time: "Waktu",
    searchBtn: "Cari Mobil Tersedia",
    sponsored: "Mobil Disponsori",
    viewAll: "Lihat Semua",
    whyChoose: "Mengapa Memilih TUBO?",
    popular: "Populer di Dekatmu",
    browseCategory: "Telusuri Kategori",
    testimonials: "Apa Kata Pengguna Kami",
    becomeHost: "Jadi Tuan Rumah",
    startHosting: "Mulai Menyewakan",
    hostDesc: "Sewakan mobilmu dan mulai hasilkan pendapatan pasif hari ini. Bergabunglah dengan ribuan tuan rumah di TUBO.",
    favorites: "Favorit",
    favoritesDesc: "Simpan mobil yang Anda suka untuk menemukannya nanti.",
    noTrips: "Tidak Ada Perjalanan",
    noTripsDesc: "Anda belum memesan mobil. Mulai jelajahi sekarang!",
    switchHost: "Beralih ke Mode Tuan Rumah",
    joinHost: "Jadi Tuan Rumah",
    hostBenefits: "Kelola daftar, cek pendapatan, dan komunikasi.",
    joinBenefits: "Dapatkan penghasilan tambahan dengan menyewakan mobilmu.",
    switch: "Alihkan",
    join: "Gabung",
    preferences: "Preferensi",
    account: "Akun",
    currency: "Mata Uang",
    language: "Bahasa",
    accountSettings: "Pengaturan Akun",
    paymentMethods: "Metode Pembayaran",
    supportInbox: "Kotak Masuk Bantuan",
    logOut: "Keluar",
    home: "Beranda",
    trips: "Trip",
    profile: "Profil",
    dashboard: "Dasbor",
    listings: "Daftar",
    inbox: "Inbox",
    menu: "Menu",
    guestMode: "Mode Tamu",
    switchToRenting: "Beralih ke penyewaan",
    hostSettings: "Pengaturan Tuan Rumah",
    payoutMethods: "Metode Pencairan",
    bookNow: "Pesan",
    book: "Pesan",
    perDay: "Per hari",
    day: "hari",
    cars: "mobil",
    locationLabel: "Lokasi",
    change: "Ubah",
    hostDashboard: "Dasbor Tuan Rumah",
    hostDashboardDesc: "Kelola armada dan pendapatan Anda.",
    weekly: "Mingguan",
    active: "Aktif",
    listNewCar: "Daftarkan Mobil Baru",
    earningsTrend: "Tren Pendapatan",
    recentBookings: "Pemesanan Terbaru",
    paid: "Lunas",
    verifiedMember: "Anggota Terverifikasi",
    yourListings: "Daftar Mobil Anda",
    hostInbox: "Kotak Masuk Tuan Rumah",
    allCities: "Semua Kota",
    showingResultsFor: "Menampilkan hasil untuk"
  },
  'Bahasa Melayu': {
    tagline: "Sewa Kereta Rakan-ke-Rakan",
    findPerfectRide: "Cari kereta idaman anda",
    exploreThousands: "Terokai ribuan kereta dari tuan rumah dipercayai",
    locationPlaceholder: "Cari bandar atau lokasi...",
    pickup: "Ambil",
    dropoff: "Kembali",
    time: "Masa",
    searchBtn: "Cari Kereta Tersedia",
    sponsored: "Kereta Ditaja",
    viewAll: "Lihat Semua",
    whyChoose: "Kenapa Pilih TUBO?",
    popular: "Popular Berdekatan Anda",
    browseCategory: "Semak Imbas Kategori",
    testimonials: "Apa Kata Pengguna Kami",
    becomeHost: "Jadi Tuan Rumah",
    startHosting: "Mula Menyewa",
    hostDesc: "Senaraikan kereta anda dan mula menjana pendapatan pasif hari ini. Sertai ribuan tuan rumah di TUBO.",
    favorites: "Kegemaran",
    favoritesDesc: "Simpan kereta yang anda suka untuk cari kemudian.",
    noTrips: "Tiada Perjalanan",
    noTripsDesc: "Anda belum menempah kereta. Mula meneroka sekarang!",
    switchHost: "Tukar ke Mod Tuan Rumah",
    joinHost: "Jadi Tuan Rumah",
    hostBenefits: "Urus penyenaraian, semak pendapatan, dan komunikasi.",
    joinBenefits: "Jana pendapatan tambahan dengan menyewakan kereta anda.",
    switch: "Tukar",
    join: "Sertai",
    preferences: "Keutamaan",
    account: "Akaun",
    currency: "Mata Wang",
    language: "Bahasa",
    accountSettings: "Tetapan Akaun",
    paymentMethods: "Kaedah Pembayaran",
    supportInbox: "Peti Masuk Bantuan",
    logOut: "Log Keluar",
    home: "Utama",
    trips: "Trip",
    profile: "Profil",
    dashboard: "Papan Pemuka",
    listings: "Senarai",
    inbox: "Inbox",
    menu: "Menu",
    guestMode: "Mod Tetamu",
    switchToRenting: "Tukar kepada menyewa",
    hostSettings: "Tetapan Tuan Rumah",
    payoutMethods: "Kaedah Pembayaran",
    bookNow: "Tempah",
    book: "Tempah",
    perDay: "Sehari",
    day: "hari",
    cars: "kereta",
    locationLabel: "Lokasi",
    change: "Tukar",
    hostDashboard: "Papan Pemuka Tuan Rumah",
    hostDashboardDesc: "Urus armada dan pendapatan anda.",
    weekly: "Mingguan",
    active: "Aktif",
    listNewCar: "Senaraikan Kereta Baru",
    earningsTrend: "Trend Pendapatan",
    recentBookings: "Tempahan Terkini",
    paid: "Dibayar",
    verifiedMember: "Ahli Disahkan",
    yourListings: "Senarai Anda",
    hostInbox: "Peti Masuk Tuan Rumah",
    allCities: "Semua Bandar",
    showingResultsFor: "Menunjukkan keputusan untuk"
  }
};

export const CATEGORIES = [
  { id: 'sedan', name: 'Sedan', icon: 'CarFront', count: 342, color: 'bg-orange-100 text-orange-600' },
  { id: 'suv', name: 'SUV', icon: 'Car', count: 256, color: 'bg-blue-100 text-blue-600' },
  { id: 'hatchback', name: 'Hatchback', icon: 'CarTaxiFront', count: 189, color: 'bg-green-100 text-green-600' },
  { id: 'van', name: 'Van', icon: 'Bus', count: 127, color: 'bg-purple-100 text-purple-600' },
  { id: 'luxury', name: 'Luxury', icon: 'Gem', count: 98, color: 'bg-yellow-100 text-yellow-600' },
  { id: 'electric', name: 'Electric', icon: 'Zap', count: 76, color: 'bg-teal-100 text-teal-600' },
];

export const FEATURES = [
  { 
    title: "Secure & Safe", 
    desc: "Verified hosts and comprehensive insurance coverage", 
    icon: 'ShieldCheck', 
    color: 'bg-orange-500' 
  },
  { 
    title: "24/7 Support", 
    desc: "Round-the-clock customer service for your peace of mind", 
    icon: 'Clock', 
    color: 'bg-blue-800' 
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Michael Chen",
    avatar: "https://i.pravatar.cc/150?u=michael",
    rating: 5,
    text: "Amazing experience! The car was in perfect condition and the host was super responsive. TUBO made my weekend trip so much easier and affordable.",
    date: "2 days ago"
  },
  {
    id: 2,
    name: "Sarah Jones",
    avatar: "https://i.pravatar.cc/150?u=sarah",
    rating: 5,
    text: "I love the flexibility. Being able to pick up the car right at the airport was a game changer. Highly recommended!",
    date: "1 week ago"
  }
];

// Regex for Smart Censorship
export const EMAIL_REGEX = /\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/gi;
export const PHONE_REGEX = /\b(\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/g;

export const INITIAL_CARS = [
  // --- BALI, INDONESIA ---
  {
    id: 'bali_1',
    hostId: 'h_bali_1',
    make: 'Suzuki',
    model: 'Jimny',
    year: 2023,
    pricePerDayIdr: 950000,
    location: 'Bali, Indonesia',
    description: 'Iconic 4x4 perfect for exploring Bali beaches and jungles.',
    imageUrl: 'https://images.unsplash.com/photo-1609520896482-70b20d44e906?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.9,
    trips: 45,
    features: ['4x4', 'AC', 'Bluetooth', '4 Seats']
  },
  {
    id: 'bali_2',
    hostId: 'h_bali_1',
    make: 'Toyota',
    model: 'Raize',
    year: 2022,
    pricePerDayIdr: 550000,
    location: 'Bali, Indonesia',
    description: 'Compact SUV, agile for narrow streets of Canggu.',
    imageUrl: 'https://images.unsplash.com/photo-1623869675781-804f75e95e51?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.8,
    trips: 120,
    features: ['Auto', 'CarPlay', 'AC', '5 Seats']
  },
  {
    id: 'bali_3',
    hostId: 'h_bali_2',
    make: 'Honda',
    model: 'Brio',
    year: 2021,
    pricePerDayIdr: 350000,
    location: 'Bali, Indonesia',
    description: 'Fuel efficient and easy to park. Best for solo or couple.',
    imageUrl: 'https://images.unsplash.com/photo-1600661653561-629509216228?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 210,
    features: ['Eco', 'AC', 'Compact', '5 Seats']
  },
  {
    id: 'bali_4',
    hostId: 'h_bali_2',
    make: 'Mitsubishi',
    model: 'Xpander',
    year: 2023,
    pricePerDayIdr: 700000,
    location: 'Bali, Indonesia',
    description: 'Spacious 7-seater, great for family trips to Ubud.',
    imageUrl: 'https://images.unsplash.com/photo-1656467476427-b25d56446676?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.9,
    trips: 88,
    features: ['7 Seats', 'Rear AC', 'Family', 'Auto']
  },
  {
    id: 'bali_5',
    hostId: 'h_bali_3',
    make: 'Mini',
    model: 'Cooper Convertible',
    year: 2020,
    pricePerDayIdr: 1800000,
    location: 'Bali, Indonesia',
    description: 'Enjoy the sun and breeze in this stylish convertible.',
    imageUrl: 'https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 5.0,
    trips: 32,
    features: ['Convertible', 'Turbo', 'Premium Audio', '2 Seats']
  },
  {
    id: 'bali_6',
    hostId: 'h_bali_3',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2022,
    pricePerDayIdr: 1200000,
    location: 'Bali, Indonesia',
    description: 'Rugged luxury SUV for any terrain in Bali.',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.8,
    trips: 65,
    features: ['Diesel', '4x4', 'Luxury', '7 Seats']
  },
  {
    id: 'bali_7',
    hostId: 'h_bali_4',
    make: 'Honda',
    model: 'HR-V',
    year: 2022,
    pricePerDayIdr: 850000,
    location: 'Bali, Indonesia',
    description: 'Modern crossover with panoramic roof.',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 92,
    features: ['Sunroof', 'Leather', 'Auto', '5 Seats']
  },
  {
    id: 'bali_8',
    hostId: 'h_bali_4',
    make: 'Toyota',
    model: 'Avanza',
    year: 2021,
    pricePerDayIdr: 400000,
    location: 'Bali, Indonesia',
    description: 'The people\'s champion. Reliable 7-seater.',
    imageUrl: 'https://images.unsplash.com/photo-1592853625601-bb9d23da126e?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.6,
    trips: 400,
    features: ['7 Seats', 'AC', 'Manual', 'Bluetooth']
  },

  // --- JAKARTA, INDONESIA ---
  {
    id: 'jkt_1',
    hostId: 'h_jkt_1',
    make: 'Hyundai',
    model: 'Ioniq 5',
    year: 2023,
    pricePerDayIdr: 2100000,
    location: 'Jakarta, Indonesia',
    description: 'Future-ready electric SUV. Odd-even policy free!',
    imageUrl: 'https://images.unsplash.com/photo-1669055920793-2b346a96a351?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.9,
    trips: 56,
    features: ['Electric', 'Autopilot', 'V2L', 'Range 400km']
  },
  {
    id: 'jkt_2',
    hostId: 'h_jkt_1',
    make: 'Toyota',
    model: 'Alphard',
    year: 2022,
    pricePerDayIdr: 2500000,
    location: 'Jakarta, Indonesia',
    description: 'First class travel experience on wheels.',
    imageUrl: 'https://images.unsplash.com/photo-1632823471565-1ec299db653e?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 5.0,
    trips: 140,
    features: ['Captain Seats', 'Sunroof', 'Privacy Glass', 'Luxury']
  },
  {
    id: 'jkt_3',
    hostId: 'h_jkt_2',
    make: 'Toyota',
    model: 'Innova Zenix',
    year: 2023,
    pricePerDayIdr: 900000,
    location: 'Jakarta, Indonesia',
    description: 'Hybrid efficiency meets captain seat comfort.',
    imageUrl: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.9,
    trips: 180,
    features: ['Hybrid', 'Captain Seats', 'Panoramic', 'TSS']
  },
  {
    id: 'jkt_4',
    hostId: 'h_jkt_2',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2021,
    pricePerDayIdr: 2200000,
    location: 'Jakarta, Indonesia',
    description: 'Executive sedan for business meetings in Sudirman.',
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.8,
    trips: 45,
    features: ['Leather', 'Ambient Light', 'CarPlay', 'Sedan']
  },
  {
    id: 'jkt_5',
    hostId: 'h_jkt_3',
    make: 'Honda',
    model: 'City Hatchback',
    year: 2022,
    pricePerDayIdr: 500000,
    location: 'Jakarta, Indonesia',
    description: 'Sporty hatchback perfect for city cruising.',
    imageUrl: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 110,
    features: ['Hatchback', 'Sport Mode', 'RS', 'Auto']
  },
  {
    id: 'jkt_6',
    hostId: 'h_jkt_3',
    make: 'Wuling',
    model: 'Air EV',
    year: 2023,
    pricePerDayIdr: 350000,
    location: 'Jakarta, Indonesia',
    description: 'Tiny electric car, easiest to park in Jakarta.',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.6,
    trips: 85,
    features: ['Electric', 'Tiny', 'Easy Park', '200km']
  },
  {
    id: 'jkt_7',
    hostId: 'h_jkt_4',
    make: 'Mitsubishi',
    model: 'Pajero Sport',
    year: 2021,
    pricePerDayIdr: 1300000,
    location: 'Jakarta, Indonesia',
    description: 'Dominating presence on the toll road.',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.8,
    trips: 130,
    features: ['Diesel', 'Sunroof', '4x4', '7 Seats']
  },

  // --- KUALA LUMPUR, MALAYSIA ---
  {
    id: 'kl_1',
    hostId: 'h_kl_1',
    make: 'Perodua',
    model: 'Myvi',
    year: 2022,
    pricePerDayIdr: 300000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'The King of the Road in Malaysia. Reliable and fast.',
    imageUrl: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.9,
    trips: 520,
    features: ['Auto', 'Smart Assist', 'Bluetooth', '5 Seats']
  },
  {
    id: 'kl_2',
    hostId: 'h_kl_1',
    make: 'Proton',
    model: 'X50',
    year: 2023,
    pricePerDayIdr: 600000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Stylish compact SUV with advanced tech.',
    imageUrl: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.8,
    trips: 150,
    features: ['Auto Park', '360 Cam', 'Turbo', 'Sunroof']
  },
  {
    id: 'kl_3',
    hostId: 'h_kl_2',
    make: 'Perodua',
    model: 'Bezza',
    year: 2021,
    pricePerDayIdr: 280000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Sedan with huge trunk space, great for airport runs.',
    imageUrl: 'https://images.unsplash.com/photo-1626077388041-33311f823272?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 300,
    features: ['Huge Trunk', 'Eco', 'Auto', 'Sedan']
  },
  {
    id: 'kl_4',
    hostId: 'h_kl_2',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    pricePerDayIdr: 900000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Turbocharged performance for the highways.',
    imageUrl: 'https://images.unsplash.com/photo-1605816988089-2d4d17a29235?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.9,
    trips: 110,
    features: ['Turbo', 'Honda Sensing', 'CarPlay', 'Leather']
  },
  {
    id: 'kl_5',
    hostId: 'h_kl_3',
    make: 'Proton',
    model: 'Saga',
    year: 2022,
    pricePerDayIdr: 250000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Budget friendly and reliable daily driver.',
    imageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.6,
    trips: 410,
    features: ['Budget', 'Bluetooth', 'AC', 'Sedan']
  },
  {
    id: 'kl_6',
    hostId: 'h_kl_3',
    make: 'Toyota',
    model: 'Vios',
    year: 2021,
    pricePerDayIdr: 500000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Smooth ride and great air conditioning.',
    imageUrl: 'https://images.unsplash.com/photo-1600706432502-75c3523dc782?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 220,
    features: ['360 Cam', 'Blind Spot', 'Auto', 'Silent']
  },
  {
    id: 'kl_7',
    hostId: 'h_kl_4',
    make: 'Mazda',
    model: 'CX-5',
    year: 2022,
    pricePerDayIdr: 1100000,
    location: 'Kuala Lumpur, Malaysia',
    description: 'Premium interior and driving dynamics.',
    imageUrl: 'https://images.unsplash.com/photo-1575090533304-543b12dc7233?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.9,
    trips: 95,
    features: ['AWD', 'Premium', 'HUD', 'Auto']
  },

  // --- SINGAPORE ---
  {
    id: 'sg_1',
    hostId: 'h_sg_1',
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    pricePerDayIdr: 3500000,
    location: 'Singapore',
    description: 'Electric performance on Singapore streets.',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.9,
    trips: 130,
    features: ['Autopilot', 'Electric', 'Glass Roof', 'Fast']
  },
  {
    id: 'sg_2',
    hostId: 'h_sg_1',
    make: 'BMW',
    model: '3 Series',
    year: 2021,
    pricePerDayIdr: 3800000,
    location: 'Singapore',
    description: 'The ultimate driving machine.',
    imageUrl: 'https://images.unsplash.com/photo-1556189250-72ba954522a8?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.8,
    trips: 90,
    features: ['M Sport', 'Laser Light', 'HUD', 'Leather']
  },
  {
    id: 'sg_3',
    hostId: 'h_sg_2',
    make: 'Toyota',
    model: 'Corolla Altis',
    year: 2020,
    pricePerDayIdr: 1800000,
    location: 'Singapore',
    description: 'Reliable hybrid sedan for city driving.',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 250,
    features: ['Hybrid', 'TSS', 'Auto', 'Sedan']
  },
  {
    id: 'sg_4',
    hostId: 'h_sg_2',
    make: 'Honda',
    model: 'Vezel',
    year: 2021,
    pricePerDayIdr: 1900000,
    location: 'Singapore',
    description: 'Compact SUV, very popular in SG.',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.6,
    trips: 210,
    features: ['Hybrid', 'Honda Sensing', 'Eco', 'Compact']
  },
  {
    id: 'sg_5',
    hostId: 'h_sg_3',
    make: 'Audi',
    model: 'A4',
    year: 2022,
    pricePerDayIdr: 3600000,
    location: 'Singapore',
    description: 'Sophisticated tech and comfort.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.8,
    trips: 70,
    features: ['Virtual Cockpit', 'Quattro', 'Leather', 'Auto']
  },
  {
    id: 'sg_6',
    hostId: 'h_sg_3',
    make: 'Mazda',
    model: '3',
    year: 2021,
    pricePerDayIdr: 1950000,
    location: 'Singapore',
    description: 'Beautiful design and great handling.',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.7,
    trips: 115,
    features: ['Mild Hybrid', 'Bose', 'HUD', 'Premium']
  },
  {
    id: 'sg_7',
    hostId: 'h_sg_4',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2021,
    pricePerDayIdr: 4500000,
    location: 'Singapore',
    description: 'Luxury chauffeur-driven experience.',
    imageUrl: 'https://images.unsplash.com/photo-1600712242805-5f786714543e?auto=format&fit=crop&w=600&q=80',
    isSponsored: true,
    available: true,
    rating: 4.9,
    trips: 60,
    features: ['Chauffeur', 'Massage', 'Air Susp', 'Luxury']
  },
   {
    id: 'sg_8',
    hostId: 'h_sg_4',
    make: 'Nissan',
    model: 'Qashqai',
    year: 2020,
    pricePerDayIdr: 1850000,
    location: 'Singapore',
    description: 'Practical family crossover.',
    imageUrl: 'https://images.unsplash.com/photo-1554223090-7e482851f4bd?auto=format&fit=crop&w=600&q=80',
    isSponsored: false,
    available: true,
    rating: 4.5,
    trips: 180,
    features: ['Turbo', 'ProPilot', 'Auto', 'SUV']
  }
];
